using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group6_PRN222_Project.Models;
using Microsoft.AspNetCore.Http;

namespace Group6_PRN222_Project.Pages.Organizer.Tickets
{
    public class CreateModel : PageModel
    {
        private readonly ProjectPrn222Context _context;

        public CreateModel(ProjectPrn222Context context)
        {
            _context = context;
        }

        public SelectList EventList { get; set; } = default!;

        public async System.Threading.Tasks.Task<IActionResult> OnGetAsync()
        {
            var selectedEventId = HttpContext.Session.GetInt32("SelectedEventId");
            var events = await _context.Events.ToListAsync();
            EventList = new SelectList(events, "EventId", "EventName", selectedEventId);

            return Page();
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        public async System.Threading.Tasks.Task<IActionResult> OnPostAsync()
        {
            ModelState.Remove("Ticket.Event");
            ModelState.Remove("Ticket.Participant");

            // QRCode is auto-generated by DB default (newid())
            Ticket.Qrcode = null;

            if (string.IsNullOrEmpty(Ticket.Status))
            {
                Ticket.Status = "Valid";
            }

            _context.Tickets.Add(Ticket);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}
