using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group6_PRN222_Project.Models;
using Microsoft.AspNetCore.Http;

namespace Group6_PRN222_Project.Pages.Organizer.Tickets
{
    public class CreateModel : PageModel
    {
        private readonly ProjectPrn222Context _context;

        public CreateModel(ProjectPrn222Context context)
        {
            _context = context;
        }

        public SelectList EventList { get; set; } = default!;
        public SelectList ParticipantList { get; set; } = default!;
        public SelectList DiscountPolicyList { get; set; } = default!;

        public async System.Threading.Tasks.Task<IActionResult> OnGetAsync()
        {
            var selectedEventId = HttpContext.Session.GetInt32("SelectedEventId");
            var events = await _context.Events.ToListAsync();
            EventList = new SelectList(events, "EventId", "EventName", selectedEventId);
            ParticipantList = new SelectList(await _context.Participants.ToListAsync(), "ParticipantId", "FullName");
            
            // Load discount policies for selected event, or all
            var policies = selectedEventId.HasValue
                ? await _context.DiscountPolicies.Where(d => d.EventId == selectedEventId && d.Status == "Active").ToListAsync()
                : await _context.DiscountPolicies.Where(d => d.Status == "Active").ToListAsync();
            DiscountPolicyList = new SelectList(policies, "PolicyId", "PolicyName");

            return Page();
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        [BindProperty]
        public int? DiscountPolicyId { get; set; }

        public async System.Threading.Tasks.Task<IActionResult> OnPostAsync()
        {
            ModelState.Remove("Ticket.Event");
            ModelState.Remove("Ticket.Participant");

            // Calculate ticket price: Event.Amount - discount%
            var ev = await _context.Events.FindAsync(Ticket.EventId);
            decimal ticketPrice = ev?.Amount ?? 0;

            if (DiscountPolicyId.HasValue)
            {
                var policy = await _context.DiscountPolicies.FindAsync(DiscountPolicyId.Value);
                if (policy != null && policy.DiscountPercent.HasValue)
                {
                    ticketPrice = ticketPrice - (ticketPrice * policy.DiscountPercent.Value / 100);
                }
            }

            // Store ticket price in PaymentStatus
            Ticket.PaymentStatus = ticketPrice.ToString("N0");
            // QRCode is auto-generated by DB default (newid())
            Ticket.Qrcode = null;
            
            if (string.IsNullOrEmpty(Ticket.Status))
            {
                Ticket.Status = "Valid";
            }

            _context.Tickets.Add(Ticket);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}
